package com.project.air_quality;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class DiferentLocationsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void diferentLocationsTest() {
    driver.get("http://localhost:8080/api/airquality");
    driver.manage().window().setSize(new Dimension(1080, 807));
    driver.findElement(By.id("states")).click();
    {
      WebElement dropdown = driver.findElement(By.id("states"));
      dropdown.findElement(By.xpath("//option[. = 'Braga']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    {
      String value = driver.findElement(By.id("states")).getAttribute("value");
      assertThat(value, is("Braga"));
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.id("city_name")).getText(), is("Braga"));
    assertThat(driver.findElement(By.id("air")).getText(), is(not("0.0")));
    assertThat(driver.findElement(By.id("category")).getText(), is(not(" ")));
    assertThat(driver.findElement(By.id("pollutant")).getText(), is(not(" ")));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("states")).click();
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.id("city_name")).getText(), is("Aveiro"));
    assertThat(driver.findElement(By.id("air")).getText(), is(not("0.0")));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("states")).click();
    {
      WebElement dropdown = driver.findElement(By.id("states"));
      dropdown.findElement(By.xpath("//option[. = 'Açores']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.id("error")).getText(), is("Data unavailable!"));
    assertThat(driver.findElement(By.id("air")).getText(), is("0.0"));
    driver.findElement(By.cssSelector("button")).click();
  }
}
